In [1]:
# SARSA in FrozenLake

In [2]:
import numpy as np
import gymnasium as gym
import session_info

In [3]:
# SARSA parameters
alpha = 0.1  # Learning rate
gamma = 0.99  # Discount factor
epsilon = 0.9  # Epsilon-greedy policy
episodes = 1000  # Number of episodes

In [4]:
# Initialize the environment
env = gym.make('FrozenLake-v1', map_name="4x4", is_slippery=False)

# Initialize Q-table
Q = np.zeros((env.observation_space.n, env.action_space.n))

def choose_action(state):
    if np.random.uniform(0, 1) < epsilon:
        return env.action_space.sample()  # Explore
    else:
        return np.argmax(Q[state, :])  # Exploit

# SARSA algorithm
for episode in range(episodes):
    state, _ = env.reset()
    action = choose_action(state)
    done = False
    while not done:
        
        next_state, reward, done, _ , _ = env.step(action)
        
        next_action = choose_action(next_state)
        
        # SARSA update
        Q[state, action] += alpha * (reward + gamma * Q[next_state, next_action] - Q[state, action])
        
        state = next_state
        action = next_action



In [5]:
# Test the learned policy
def test_policy(n_episodes=100):
    successes = 0
    for _ in range(n_episodes):
        state, _ = env.reset()
        done = False
        while not done:
            action = np.argmax(Q[state, :])
            state, reward, done, _ , _ = env.step(action)
            if reward == 1:
                successes += 1
    return successes / n_episodes

success_rate = test_policy()
print(f"Success rate: {success_rate:.2%}")

# Display the learned Q-table
print("\nLearned Q-table:")
print()
print(Q)



Success rate: 100.00%

Learned Q-table:

[[4.88794765e-03 1.08165099e-02 2.18294008e-03 5.80715282e-03]
 [4.81234316e-03 0.00000000e+00 3.59987151e-03 3.10253151e-03]
 [1.22774164e-03 1.96991471e-02 5.38850950e-04 5.41570074e-03]
 [3.42846301e-03 0.00000000e+00 4.78506016e-04 7.85198481e-07]
 [1.04041691e-02 2.68633035e-02 0.00000000e+00 5.95100167e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 7.98957512e-02 0.00000000e+00 1.95004590e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [1.45370775e-02 0.00000000e+00 4.49285043e-02 7.21212495e-03]
 [1.78181064e-02 4.27806398e-02 1.18021772e-01 0.00000000e+00]
 [2.10832447e-02 2.97746837e-01 0.00000000e+00 6.30966030e-03]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 0.00000000e+00 0.00000000e+00]
 [0.00000000e+00 7.45863012e-02 2.46904472e-01 2.44073124e-02]
 [5.79258984e-02 2.10681771e-01 9.28210201e-01 3.40594553e-02]
 [0.00000000e+

In [6]:
# Testing the results

# Print learned policy
print("Learned Policy:")
print("===============")
print()
policy = np.argmax(Q, axis=1)
policy_symbols = ['←', '↓', '→', '↑', 'S', 'G', 'H']  # Up, Right, Down, Left

# Mark special positions
desc = env.unwrapped.desc
for i in range(4):
    for j in range(4):
        if desc[i][j] == b'H':
            policy[i*4+j%4] = 6
        elif desc[i][j] == b'G':
            policy[i*4+j%4] = 5
        elif desc[i][j] == b'S':
            policy[i*4+j%4] = 4

for i in range(4):
    for j in range(4):
        print(policy_symbols[policy[i*4 + j]], end=' ')
    print()
  
    

# Print value function
print("\nValue Function:")
print("===================")
V = np.max(Q, axis=1)
for i in range(4):
    for j in range(4):
        print(f"{V[i*4 + j]:.2f}", end=' ')
    print()


# Test the learned policy
env = gym.make('FrozenLake-v1', is_slippery=False, render_mode='human')
state, _ = env.reset()
state = int(state)
done = False
total_reward = 0

while not done:
    action = np.argmax(Q[state, :])
    state, reward, terminated, truncated, _ = env.step(action)
    state = int(state)
    done = terminated or truncated
    total_reward += reward
    env.render()

print(f"\nTotal reward: {total_reward}")

Learned Policy:

S ← ↓ ← 
↓ H ↓ H 
→ → ↓ H 
H → → G 

Value Function:
0.01 0.00 0.02 0.00 
0.03 0.00 0.08 0.00 
0.04 0.12 0.30 0.00 
0.00 0.25 0.93 0.00 

Total reward: 1.0


In [7]:
session_info.show(html=False)

-----
gymnasium           0.29.1
numpy               1.26.4
session_info        1.0.0
-----
IPython             8.26.0
jupyter_client      8.6.2
jupyter_core        5.7.2
-----
Python 3.12.3 (main, Sep 11 2024, 14:17:37) [GCC 13.2.0]
Linux-5.15.153.1-microsoft-standard-WSL2-x86_64-with-glibc2.39
-----
Session information updated at 2024-09-19 16:02
